#!/bin/bash

export FLASK_APP=./evodoc/evodoc.py

if [ $1 == "run" ] ; then
    python3 -m flask run
elif [ $1 == "install" ] ; then
    python3 -m setup install
elif [ $1 == "db" ] ; then
    if [ $# == 2 ] ; then
        python3 -m flask db $2
    elif [ $# == 1 ] ; then
        python3 -m flask db
    fi
fi
