"""empty message

Revision ID: 265db19e293b
Revises: e6c014f6c47d
Create Date: 2018-04-23 15:31:55.646128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '265db19e293b'
down_revision = 'e6c014f6c47d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('activated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'activated')
    # ### end Alembic commands ###
