"""empty message

Revision ID: 7689aa29309b
Revises: 3150c1fa649e
Create Date: 2018-04-27 16:54:40.507061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7689aa29309b'
down_revision = '3150c1fa649e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'module', 'project', ['project_id'], ['id'])
    op.create_foreign_key(None, 'module_perm', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'module_perm', 'module', ['module_id'], ['id'])
    op.create_foreign_key(None, 'project_perm', 'project', ['project_id'], ['id'])
    op.create_foreign_key(None, 'project_perm', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_perm', type_='foreignkey')
    op.drop_constraint(None, 'project_perm', type_='foreignkey')
    op.drop_constraint(None, 'module_perm', type_='foreignkey')
    op.drop_constraint(None, 'module_perm', type_='foreignkey')
    op.drop_constraint(None, 'module', type_='foreignkey')
    # ### end Alembic commands ###
