"""empty message

Revision ID: 8447869af9bf
Revises: 7689aa29309b
Create Date: 2018-04-28 13:25:16.156301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8447869af9bf'
down_revision = '7689aa29309b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('update', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('package')
    # ### end Alembic commands ###
