"""empty message

Revision ID: 858d091d4a38
Revises: aea47358fa62
Create Date: 2018-04-04 11:53:28.694055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858d091d4a38'
down_revision = 'aea47358fa62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=47), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_token')
    # ### end Alembic commands ###
