"""empty message

Revision ID: e6c014f6c47d
Revises: fa7c56814f71
Create Date: 2018-04-23 09:19:23.787440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c014f6c47d'
down_revision = 'fa7c56814f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_token_user_id_fkey', 'user_token', type_='foreignkey')
    op.create_foreign_key(None, 'user_token', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_token', type_='foreignkey')
    op.create_foreign_key('user_token_user_id_fkey', 'user_token', 'user_type', ['user_id'], ['id'])
    # ### end Alembic commands ###
