"""empty message

Revision ID: fa7c56814f71
Revises: 79fc6d90f32a
Create Date: 2018-04-23 08:40:46.034974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7c56814f71'
down_revision = '79fc6d90f32a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_token', 'user_type', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_token', type_='foreignkey')
    # ### end Alembic commands ###
